# Generated by Django 5.2.14 on 2026-05-12 22:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0003_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTypeModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_types', to='launcher.module', verbose_name='Módulo')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='launcher.projecttype', verbose_name='Tipo de proyecto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
