# Generated by Django 5.2.14 on 2026-05-15 22:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('launcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('short_name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('business_name', models.CharField(max_length=255, verbose_name='Razón social')),
                ('initials', models.CharField(max_length=10, verbose_name='Siglas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='Número')),
                ('description', models.TextField(verbose_name='Objeto')),
                ('sign_date', models.DateField(verbose_name='Fecha de firma')),
                ('expiration_date', models.DateField(verbose_name='Fecha de fin')),
                ('duration_days', models.IntegerField(verbose_name='Duración')),
                ('amount_before_tax', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Importe sin IVA')),
                ('amount_after_tax', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Importe con IVA')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('cancelled', 'Cancelado'), ('completed', 'Terminado')], default='active', max_length=20, verbose_name='Estado')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.currency', verbose_name='Moneda')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='launcher.project', verbose_name='Proyecto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_links', to='legal_instruments.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_links', to='legal_instruments.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='clients',
            field=models.ManyToManyField(related_name='contracts', through='legal_instruments.ContractClient', to='legal_instruments.client', verbose_name='Clientes'),
        ),
    ]
